version: "3.9"

services:
  livekit:
    container_name: streaming-app-livekit
    image: livekit/livekit-server:v1.5.3 # Use the latest version
    ports:
      - ${LIVE_KIT_HTTP_PORT}:${LIVE_KIT_HTTP_PORT} # HTTP port
      - ${LIVE_KIT_WSS_PORT}:${LIVE_KIT_WSS_PORT} # WebSocket port
      - "7882:7882" # RTP/RTCP port range (UDP)
    environment:
      LIVEKIT_KEYS: "${LIVE_KIT_API_KEY}: ${LIVE_KIT_SECRET_KEY}"
    command: [ "--dev", "--node-ip=0.0.0.0" ]

  streaming-app-db:
    container_name: streaming-app-db
    image: postgres:16.1
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  streaming-app:
    container_name: streaming-app
    depends_on:
      - streaming-app-db
      - swagger-ui
    restart: on-failure
    image: streaming-app
    build: .
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=streaming-app-db
      - DB_PORT=${DB_PORT}
      - LIVE_KIT_SECRET_KEY=${LIVE_KIT_SECRET_KEY}
      - LIVE_KIT_API_KEY=${LIVE_KIT_API_KEY}
      - LIVE_KIT_HOST_HTTP_LOCAL=${LIVE_KIT_HOST_HTTP_LOCAL}

  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/docs
    restart: always
    environment:
      - SWAGGER_JSON=/docs/swagger.yml
    container_name: swagger-ui