version: "3.9"

services:
  streaming-app-db:
    container_name: streaming-app-db
    image: postgres:16.1
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  streaming-app:
    container_name: streaming-app
    depends_on:
      - streaming-app-db
    restart: on-failure
    image: streaming-app
    build: .
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=streaming-app-db
      - DB_PORT=${DB_PORT}
